name: 🚀 Run doxygen

on:
  create:
    tags:
      - v*

jobs:
  run:
    name: 🚀 Run doxygen
    runs-on: ubuntu-latest

    steps:
      - name: run doxygen
        shell: bash
        run: |
          sudo apt install doxygen
          rm -rf html
          doxygen -g
          doxygen
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: html/