name: 🚀 Run unittesting

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  run:
    name: 🚀 Run unittesting
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run unittesting
        shell: bash
        run: |
          python3 test_tree.py
